### ISSUE TITLE
Warning : Property "$createElement" was accessed during render but is not defined on instance.

### ISSUE THREAD

**Issue by romain-aragon** [ImGelu/vue-treeselect#1]
Thanks for maintain that cool lib.
We have a warning during execution.
[Property "$createElement" was accessed during render but is not defined on instance.](https://github.com/megafetis/vue3-treeselect/issues/2#top)

To fix that you can delete all lines "var h = this.$createElement;" in dist/vue-treeselect.umd.js and dist/vue-treeselect.comon.js
Seems the variable h is never used, in any case, because $createElement is not defined, that will change nothing (except the warning in the console ;-)

That is working for me in dev & prod.

**Comment by tak-ho-raspect** [comment]
+1 
I also get the warning, will we have any fix on that instead of the workaround for deleting codes in file? Thanks!

**Comment by tak-ho** [comment]
@ImGelu I want to create a pull request but no permission to do that, could you please grant me? Thanks

**Comment by ImGelu** [comment]
Hi @tak-ho, you should be able to do that now. LMK if there are any problems :)

**Comment by tak-ho** [comment]
@ImGelu Thanks! merge request created: https://github.com/ImGelu/vue-treeselect/pull/2

**Comment by ImGelu** [comment]
Fixed on v0.1.8
